// Java 8
package com.ctm.model;

public enum Cities {
    DELHI, MUMBAI, KOLKATA, BENGALURU, CHENNAI, HYDERABAD, AHMEDABAD, PUNE, SURAT, JAIPUR,
    KANPUR, LUCKNOW, NAGPUR, INDORE, PATNA, BHOPAL, VADODARA, GHAZIABAD, LUDHIANA, AGRA,
    NASHIK, FARIDABAD, MEERUT, RAJKOT, KALYAN_DOMBIVLI, VARANASI, SRINAGAR, AURANGABAD, DHANBAD, COIMBATORE
}
